### ISSUE TITLE
Symfony integration sample

### ISSUE THREAD

**Issue by josecelano** [SimpleBus/SymfonyBridge#2]
It would be great to have a sample Symfony application with SimpleBus integrated.

I have found these samples:

https://github.com/tyx/ddd-sample-symfony
https://github.com/leopro/trip-planner
https://github.com/beberlei/litecqrs-php/blob/master/example/SymfonyExample.md

but it seems SimpleBus is the most complete library.

would be possible to use RabbitMQ or ActiveMQ to store/dispatch events?
would be possible to catch some events in the same symfony app and others events in external app workers?

Example:

````
<?php

class UserController extends Controller
{
    public function registerAction()
    {
        $command = new RegisterUserCommand(...);

        $this->get('command_bus')->handle($command);

        ...
    }
}
````

- I want to handle events asynchronously (using ACtiveMq or RabbitMQ).
- I want to register an event handler (same symfony app) using a service tag. For example send welcome email.
- I want to create a worker (for example in Java to make clear it will be independent app/server) to resize profile images (user uploads a profile image when he signs up).

could I suscribe to the event NewUserWasRegistered on worker server or add a command handler for the command RegisterUserCommand?

My question is: could be the SimpleBus used as common bus for internal comunication in the same application infraestrucutre (Symfony) and for comunication with external module? Using the same instance of SimpleBus or not.

**Comment by matthiasnoback** [comment]
Thanks for submitting your ideas. I think a sample application would be nice!

Everything you mention is possible since everything about SimpleBus is easily extensible. Especially in the new version, which will soon be released.

If you have specific questions about how to achieve certain goals that you mention here, please open a new issue. I'll consider this issue to be a request for a demo app :)

**Comment by josecelano** [comment]
Hi Matthias:

**Comment by josecelano** [comment]
I have fixed the problem. Now I want to use the command bus to send messages to an ActiveMQ or RabbitMQ queue. Could you point me in the right way. I supposed I have to use a custom command bus, is that right?

Option 1: Use SpecializedMiddleware

````
use SimpleBus\Message\Bus\Middleware\MessageBusMiddleware;
use SimpleBus\Message\Message;

class SpecializedMiddleware implements MessageBusMiddleware
{
    public function handle(Message $message, callable $next)
    {
        // do anything you like: 
        // 1.- connect to the ActiveMQ server
        // 2.- serialize event
        // 3.- insert into the queue

        // then let the next middleware do its job
        $next($message);

        // finally, you are allowed to do some other things
    }
}
````

Option 2: Implement and EventHandler

1.- Implement EventHandler
2.- Make the EventHandler send the message to the message queue server

And waht about the inverse process: get and event from message queue server and inject it in the event bus?

**Comment by matthiasnoback** [comment]
Hi! It's great that you're setting this up as a demo app. I'll look into it later. For now first an answer to your question: it's the best option to use middleware here, since middleware allows you to intercept any message. See the example near the bottom of this page: http://simplebus.github.io/MessageBus/doc/command_bus.html

The inverse process requires another command bus instance I think. It would usually be defined in a different project and process, but it might just as well be done in the same project of course.

**Comment by matthiasnoback** [comment]
Closing this now, since it doesn't require any action from me (right?).

**Comment by josecelano** [comment]
It's OK. Here is another sample using the library:

https://github.com/blockcypher/php-wallet-sample
