### ISSUE TITLE
Message validation middleware

### ISSUE THREAD

**Issue by tmilos** [SimpleBus/SymfonyBridge#24]
It would be helpful to have a out of the box message validation middleware included in the command_bus stack. It will use the standard symfony's ValidatorInterface to validate messages. It's priority should be greatest so it executes first before all others. 

Will make a PR soon.

**Comment by tmilos** [comment]
Though... not sure if this bundle is the place for the middleware class, or it should go to the MessageBus lib. Please clarify, so I can make a PR.

**Comment by ruudk** [comment]
Maybe related: https://github.com/SimpleBus/MessageBus/issues/19

**Comment by matthiasnoback** [comment]
Hi @tmilos, as described in the issue pointed out by @ruudk: I don't recommend using middleware to validate a command, especially in the case where commands are instantiated because of a user action (they clicked a button, filled in a form, etc.). You should validate the command before handing it over to the command bus in the first place, which allows you to give the user some feedback. Then wherever the data from the command is used inside your domain model, add assertions and throw exceptions when anything is not right.

**Comment by tmilos** [comment]
Sure, users of the bus should behave and do themselves the validation prior to calling the bus and present a nice message to their users. But, each layer should do its own validation, and if the bus does not guarantee that delivered messages are valid, then each command handler must have additional code and dependencies to do the validation himself. So, if there's no a validation middleware present in the stack, I would have to put in each of my handlers  

``` php

public function validate($command) 
{
    $errors = $this->validator->validate($command);
    if (count($errors) > 0) {
        throw new InvalidCommandExceptiion((string)$errors, $errors);
    }

    // now do interesting stuff...
}

Making each of the handlers dependent on the validator service and repeating these 4 lines of code in each of them seems quite tedious. That's not what you're thinking, right? Please explain if I'm wrong.

**Comment by matthiasnoback** [comment]
Right, no that's not what I meant. I mean command validation is one thing, but domain model validation (also known as invariant protection) is another thing. Once the command is actually being handled, rely on exceptions to be thrown inside the domain classes themselves.

**Comment by tmilos** [comment]
Yes, domain throwing exceptions is great, but I'm having trouble with validation that requires additional queries, like for example uniqueness of a username. Can not base on the persistence layer DBALExceptions since then EntityManager closes and can not use it anymore. Then, what do you think about domain validation component listening on doctrine pre_persist event? Just came to my mind, though didn't see something like that before.

**Comment by matthiasnoback** [comment]
Ah, right. You can still have that check both in the command validator (DoctrineBundle comes with a Unique constraint validator) and in the domain layer (where you just query the repository and thrown an exception if a username is already in use).

**Comment by tmilos** [comment]
Ok, so you don't find this as a part of the standard configuration. I'll have to figure and make something on my own. Still don't see how a command validation middleware can hurt. Anyway, thanks. Please close the issue if you don't find it relevant anymore.

**Comment by matthiasnoback** [comment]
Of course, it should be very easy to create and use your own validation middleware (and, why not create a package for it? ;)).
I believe it shouldn't be the recommended way to validate your commands, since inside the middleware there's no way to talk back to the user anyway, except maybe to just throw an exception, but that is not useful at all. In that case, you'd better fall back to the domain-level validations.

**Comment by cmodijk** [comment]
I'm closing this because it is open for a long time and i belief it should not be done as a core component for `SimpleBus`.
