### ISSUE TITLE
Saga support

### ISSUE THREAD

**Issue by tmilos** [SimpleBus/SymfonyBridge#25]
I tried to implement sagas in terms of qandidate-labs/broadway - aka a process mananger. It listens to domain events from event_bus (caused by already executing commands triggered by ``WrapsMessageHandlingInTransaction`` from doctrine-orm-bridge) and depending on its internal state runs other commands trough command_bus. I don't use any async middlewares. 

Problem I had encounter is that commands dispatched by process manager are not executed right away due to already executing command (that triggered the event PM acts upon) but are rather queued by ``FinishesHandlingMessageBeforeHandlingNext``, so PM is unable to catch the eventual exception and properly update its state and take corresponding action. 

So, I have several proposals
 * parallelism/concurrency of the message handling stack should be configurable with three options: queue (as it is now), block (throw exception), allow (just pass it trough) 
 * order or ``FinishesHandlingMessageBeforeHandlingNext`` and ``WrapsMessageHandlingInTransaction`` should be reversed so messages are queued only in a transaction, so events disptached by ``WrapsMessageHandlingInTransaction`` are not isolated and queued.

Afterall, if that won't universally fit every usage, the configuration of this bundle should be more flexible to somehow allow sagas.

I can do PR, just want to consult first about the solution.

**Comment by matthiasnoback** [comment]
Hi @tmilos, interesting!

I feel that at some point you may be better off making the jump to Broadway in the first place. SimpleBus can be limited in some ways. Still, if I remember correctly, Broadway's command bus has the same "blocking" behavior as SimpleBus has.

Each transaction should wrap exactly one command being handled, since one command should modify just one aggregate. If we handle other commands within one transaction, they may endanger the successfulness of the transaction. That's why we shouldn't change the blocking behavior, and also not reverse the order of middlewares (if you still want this, you're free to do so of course - it's not easily configurable but definitely doable).

As for sagas, I'd say it doesn't matter when exactly the command is being issued. The saga itself doesn't need to be aware of synchronousness or asynchronousness. It just hands over a new command to the command bus. Waiting for an exception makes no sense really. If the exception represents a domain-related failure of the long-running process, you'd be better of by dispatching a new event (SomethingSomethingFailed) and make the saga respond to that event. That's what a saga should be: it responds to events by issueing new commands. It also knows how to compensate failures.

I hope this helps in any way!

**Comment by tmilos** [comment]
Actually, my point is that domain events should be dispatched after the transaction has been committed and command bus unblocked, since otherwise, event listeners can not synchronously run another commands as a consequence of the event they listen to, which in turn was a consequence of the first command.

**Comment by tmilos** [comment]
BTW Broadway looked too big to start with.

**Comment by matthiasnoback** [comment]
Right, I get what you mean. It's designed to be like this: when a command triggers new events, these are supposed to be handled right away, and new commands should wait until all events for the previous command have been handled.

Also, SimpleBus is designed with optional asynchronousness in mind. So you don't have to, but you can't rely on the synchronicity of command handlers as well (there's not an easy way to get a return value from them for example).

**Comment by tmilos** [comment]
Yes that asynchronousness... :) 
Though... Broadway seems to support domain events but together with event sourcing. I find simplebus nice since it does not enforce me to do event sourcing.

**Comment by matthiasnoback** [comment]
Nice to hear that! Yes, it doesn't force you to do that. It does however more or less force you to separate commands from queries, though not necessarily with separated data stores.

**Comment by tmilos** [comment]
Yes, CQRS is great, but I don't dare to switch to event sourcing... yet. I'll try to play a bit more with sagas and simpelbus, and maybe come back later. Thanks for the chat.

**Comment by matthiasnoback** [comment]
Thank you too, it's been very interesting to me. Maybe it can serve as some non-official documentation for others too ;) Closing this now, thanks!
