### ISSUE TITLE
Priority support for registrering of subscribers

### ISSUE THREAD

**Issue by ruudk** [SimpleBus/SymfonyBridge#30]
I'd like a specific subscriber to be executed before another subscriber. But there is no support for priority.
But the middlewares do have support. Any special reason for this?

Should I submit a PR to fix it?

**Comment by cmodijk** [comment]
I think this is because of the fact that if events are going trough something like RabbitMQ you don't have a guarantee that the subscribers are beging processed in order. @matthiasnoback wrote a artikel about the commands and events on his blog maybe this is helpful? 
* http://php-and-symfony.matthiasnoback.nl/2015/01/from-commands-to-events/

**Comment by matthiasnoback** [comment]
The lack of priority forces you to not rely on a particular order. If you
need a chain of actions you need to find some other solution.

**Comment by matthiasnoback** [comment]
I forgot to mention that I'd be happy to think about your case if you like!
