### ISSUE TITLE
Why ProxyManager?

### ISSUE THREAD

**Issue by garak** [SimpleBus/SymfonyBridge#66]
I see that 887c54c5030337b863a00c39bead8abd24dd7e54 introduced a dependency on symfony/proxy-manager-bridge, apparently without using it.
Is it really needed?

**Comment by cmodijk** [comment]
Ping @caciobanu

**Comment by ruudk** [comment]
I commented on this issue in the PR, see https://github.com/SimpleBus/SymfonyBridge/pull/58#pullrequestreview-78890572

The issue here, is that 
https://github.com/SimpleBus/DoctrineORMBridge/blob/d77e741ada824cf1bafdbdcc940e529af0fc9ddd/src/MessageBus/WrapsMessageHandlingInTransaction.php#L44
requires the ProxyManager to be present.

I think we should do this:
* Remove the dependency from SymfonyBridge and move it to `suggest`
* Check for the presence of ProxyManager when you enable DoctrineOrmBridgeExtension, error when it not present (BC change)

WDYT?

**Comment by garak** [comment]
I think that it doesn't make sense to keep a dependency in this package because of a different package. If DoctrineORMBridge needs the bridge, the dependency should be there.

**Comment by caciobanu** [comment]
The dependency is for DoctrineORMBridge to work correctly but that package, if I understood correctly, can be used outside of symfony that is why the dependency was added to this repo.

I think what @ruudk suggested could be a good alternative.

**Comment by garak** [comment]
But the opposite is true, also: this package can be used without DoctrineORMBridge

**Comment by caciobanu** [comment]
Yes. I think that the proposal @ruudk made is the best path to follow. What do you say ?

**Comment by garak** [comment]
It's a solution.
A possible alternate solution could be to create a new package, something like SimpleBus/SymfonyDoctrineORMBridge, that requires all the needed stuff.

**Comment by ruudk** [comment]
@caciobanu Can you make a PR to drop the proxy-manager dependency (like it was before SF 4 PR)? Or does it fail on Travis?

@garak Hmm, not really a fan of creating yet another bundle/bridge 😉

**Comment by caciobanu** [comment]
@ruudk it will fail on travis.

**Comment by garak** [comment]
@caciobanu if dependency is only needed for tests, we can move it to `require-dev`

**Comment by caciobanu** [comment]
Yes, but people using this and enabling the doctrine orm bridge will get sudden errors without knowing what happened.

**Comment by garak** [comment]
If that's the problem, just add a note somewhere (e.g. a `CHANGELOG`) to warn about it.

**Comment by caciobanu** [comment]
The idea is that when an errors is thrown by the ORM and we are in a transaction started by **WrapsMessageHandlingInTransaction** in that class at https://github.com/SimpleBus/DoctrineORMBridge/blob/d77e741ada824cf1bafdbdcc940e529af0fc9ddd/src/MessageBus/WrapsMessageHandlingInTransaction.php#L44 there is some logic to reset the manager which fails due to symfony 4 container changes.

**Comment by caciobanu** [comment]
I will give @ruudk idea a try to see how it goes.

**Comment by ruudk** [comment]
@caciobanu Maybe we should enforce that ManagerRegistry is always an instance of `ProxyManager\Proxy\LazyLoadingInterface`. We could release that as a new major version, add it to the UPGRADE.md, and also add it to composer `suggest`?

**Comment by cmodijk** [comment]
Just a side note to all as i suggested in the [Mono repository](https://github.com/SimpleBus/MessageBus/issues/79) issue eventually i think we should start to think on splitting these 'Bundles' which are now grouped in this package for every implementation one with the Mono repository creating these bridges should be easier to do and then we can add these required items

**Comment by caciobanu** [comment]
@ruudk @garak take a look at #68.

**Comment by garak** [comment]
LGTM
